CREATE TABLE IF NOT EXISTS `users` (
    `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(`id`),
    `name` VARCHAR(300) NOT NULL DEFAULT 'default',
    `hash` VARCHAR(300) NOT NULL DEFAULT '',
    `admin` BOOLEAN NOT NULL DEFAULT false,
    `config` VARCHAR(1000) NOT NULL DEFAULT '{"main_color":"#FFFFFF","question_color":"#FFFFFF","font_color":"#FFFFFF"}'
);

CREATE TABLE IF NOT EXISTS `votes` (
    `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(`id`),
    `description` VARCHAR(1000) NOT NULL,
    `admin_id` MEDIUMINT NOT NULL
);

CREATE TABLE IF NOT EXISTS `votes_questions` (
    `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(`id`),
    `vote_id` MEDIUMINT NOT NULL,
    `description` VARCHAR(1000) NOT NULL,
	`q1` VARCHAR(1000) NOT NULL,
	`q2` VARCHAR(1000) NOT NULL,
	`q3` VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS `responce` (
    `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(`id`),
    `vote_id` MEDIUMINT NOT NULL,
    `vote_question_id` MEDIUMINT NOT NULL,
    `q1` INT NOT NULL DEFAULT 0,
    `q2` INT NOT NULL DEFAULT 0,
    `q3` INT NOT NULL DEFAULT 0,
    `user_id` MEDIUMINT NOT NULL
);