openapi: 3.0.0
info:
  title: Voting API
  description: API для голосования и управления администраторами
  version: 1.0.0
servers:
  - url: ${API_HOST}
    description: Production server

paths:
  /admin/signin/:
    post:
      summary: Регистрация администратора
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                hash:
                  type: string
                  example: yourpassword
      responses:
        '201':
          description: Успех
        '400':
          description: Ошибка валидации данных
  /admin/login/:
    post:
      summary: Вход администратора
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                hash:
                  type: string
                  example: yourpassword
      responses:
        '200':
          description: Успех
        '401':
          description: Неверные данные
  /admin/logout/:
    post:
      summary: Выход администратора
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
      responses:
        '200':
          description: Успех
  /admin/me/:
    post:
      summary: Информация об администраторе
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
      responses:
        '200':
          description: Успех
  /user/signin/:
    post:
      summary: Регистрация пользователя
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: user123
                hash:
                  type: string
                  example: yourpassword
      responses:
        '201':
          description: Успех
        '400':
          description: Ошибка валидации данных
  /user/login/:
    post:
      summary: Вход пользователя
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: user123
                hash:
                  type: string
                  example: yourpassword
      responses:
        '201':
          description: Успех
        '400':
          description: Ошибка валидации данных
  /user/logout/:
    post:
      summary: Выход пользователя
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: user123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
      responses:
        '200':
          description: Успех
  /user/me/:
    post:
      summary: Информация о пользователя
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: user123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
      responses:
        '200':
          description: Успех
  /vote/create/:
    post:
      summary: Создание опроса
      tags:
        - Vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
                votes:
                  type: object
                  properties:
                    description:
                      type: string
                      example: Ваше описание опроса
                    questions_desc:
                      type: array
                      items:
                        type: object
                        properties:
                          description:
                            type: string
                            example: Ваше описание вопроса
                          q1:
                            type: string
                            example: Первый вопрос
                          q2:
                            type: string
                            example: Второй вопрос
                          q3:
                            type: string
                            example: Третий вопрос
      responses:
        '200':
          description: Успех
  /vote/get/:
    post:
      summary: Получение опроса
      tags:
        - Vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
                voteId:
                  type: integer
                  example: 12
      responses:
        '200':
          description: Успех
  /vote/adminVotes/:
    post:
      summary: Получение опроса
      tags:
        - Vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
      responses:
        '200':
          description: Успех
  /vote/toVote/:
    post:
      summary: Новый результат опроса пользователя
      tags:
        - Vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
                voteId:
                  type: integer
                  example: 12
                vote:
                  type: array
                  items:
                    type: object
                    properties:
                      q1:
                        type: integer
                        example: 1
                      q2:
                        type: integer
                        example: 2
                      q3:
                        type: integer
                        example: 3       
      responses:
        '200':
          description: Успех
  /vote/getResult/:
    post:
      summary: Получение опроса
      tags:
        - Vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin123
                token:
                  type: string
                  example: bd16a322-907c-49d7-b05f-7227b52b57d4
                voteId:
                  type: integer
                  example: 12
      responses:
        '200':
          description: Успех